#!/bin/sh

mute=`amixer get Master | awk -F'[]%[]' '/%/ {print $5}' | head -n 1`
vol=`amixer get Master | awk -F'[]%[]' '/%/ {print $2}' | head -n 1`

if [ -z "$vol" ]; then
    bar=☓
elif [ "$vol" -eq "0" ]; then
    bar="  "
elif [ "$vol" -lt "13" ]; then
    bar=▁
elif [ "$vol" -lt "25" ]; then
    bar=▂
elif [ "$vol" -lt "38" ]; then
    bar=▃
elif [ "$vol" -lt "50" ]; then
    bar=▄
elif [ "$vol" -lt "63" ]; then
    bar=▅
elif [ "$vol" -lt "75" ]; then
    bar=▆
elif [ "$vol" -lt "88" ]; then
    bar=▇
else
    bar=█
fi

if [ "$mute" == "off" ]
then
  echo "<fc=#dc322f><icon=vol-mute.xbm/>$bar</fc>"
else
  echo "<fc=#6c71c4><icon=vol-hi.xbm/></fc>$bar"
fi
